"""another cool  Migration

Revision ID: 8f0eba913d03
Revises: 33ee2b3f3d47
Create Date: 2019-02-27 10:34:35.404223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0eba913d03'
down_revision = '33ee2b3f3d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
